twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        avis_doc_directory: '%avis_doc_directory%'
        contrat_doc_directory: '%contrat_doc_directory%'

when@test:
    twig:
        strict_variables: true
