parameters:
    app.role_manager: 'ROLE_USER_MANAGER'
    app.role_juridique: 'ROLE_USER_JURIDIQUE'
    app.role_boss_juridique: 'ROLE_USER_BOSS_JURIDIQUE'

    preuves_folder: '%kernel.project_dir%/public/uploads/'
    obligation_folder: '%kernel.project_dir%/public/uploads/'
    avis_doc_directory: '%kernel.project_dir%/public/uploads/'
    mod_contrat_folder: '%kernel.project_dir%/public/uploads/'
    contrat_doc_directory: '%kernel.project_dir%/public/uploads/'

    generated_pdf_dir: '%kernel.project_dir%/public/generated/'

    app.test_mail: '%env(TEST_MAIL)%'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Mail\DefaultMailService:
        arguments:
            $testMail: '%app.test_mail%'

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags:
            - ldap
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: 'AD-Serv'
                port: 389
                encryption: none
                options:
                    protocol_version: 3
                    referrals: false
